Encoder gray + signed/unsigned
PandABlocks/PandABlocks-FPGA pull request #39
Opened 2021-02-10 14:14 UTC by valerixb

Possibility to choose between gray and binary encoding and signed/unsigned value for absolute encoders; default is unsigned binary. Description has been updated as per GTHIBAUX comment on PR #30, to show that this affects absolute and not incremental encoders. This pull request also solves issue #34 (position_sign_extension is not optional).

2021-02-10 14:28 UTC, Araneidae commented on common/hdl/shifter_in.vhd
> +				if (clock_i = '1') then
I notice that this commit introduces tabs that were not previously present in the source.

I suspect this may be a widespread issue.  @thomascobb , it might be worth have a look at the code base to flush out any creeping tab characters.

Contributors: please configure your editor appropriately!

2021-02-11 13:54 UTC, valerixb commented on common/hdl/shifter_in.vhd
> +				if (clock_i = '1') then
Sorry: rookie mistake. I fixed all the extra TABs, leaving only those in makefiles, device tree files (dts) and .prn files; I committed the changes to https://github.com/valerixb/PandABlocks-FPGA/tree/encoder_gray. 
I am no real expert of git: what do you think is the best way to bring those changes here?
Thank you; best regards

2021-04-01 15:25 UTC, thomascobb requested changes

2021-04-01 15:25 UTC, thomascobb commented on common/hdl/defines/support.vhd
> +constant c_UNSIGNED_BINARY_ENCODING  : std_logic_vector(1 downto 0) := "00";
I think that the existing behaviour is `SIGNED_BINARY_ENCODING`. If this is correct, please can we assign `00` to that, so that an upgrade will be backwards compatible? If we merge as is, then we will break anyone with a 32-bit signed encoder...

2021-04-01 15:25 UTC, thomascobb commented on targets/PandABox/blocks/inenc/inenc.block.ini
> +0: Unsigned Binary
Change would also need to be made here

2021-04-01 15:25 UTC, thomascobb commented on targets/PandABox/blocks/outenc/outenc.block.ini
> +0: Unsigned Binary
And here

2021-04-01 15:40 UTC, valerixb commented on common/hdl/defines/support.vhd
> +constant c_UNSIGNED_BINARY_ENCODING  : std_logic_vector(1 downto 0) := "00";
Tom, it was an explicit request from Soleil: as in the original panda code there was no sign extension (I think it was a bug), using "unsigned binary" as default (00) makes the change backwards compatible. If we put "signed binary" we brake compatibility with all FW before #29 (september 2020), which I think is the bulk of the Pandas. What do you think?

2021-04-01 15:50 UTC, thomascobb commented on common/hdl/defines/support.vhd
> +constant c_UNSIGNED_BINARY_ENCODING  : std_logic_vector(1 downto 0) := "00";
ok, that makes sense, I will merge this as is

2021-04-01 15:51 UTC, thomascobb approved these changes

2021-04-01 16:41 UTC, merged