Add std_dev calculation for PCAP module
PandABlocks/PandABlocks-FPGA pull request #68
Opened 2021-11-09 10:02 UTC by shu-soleil

2021-12-03 13:52 UTC, shu-soleil commented
make_zpkg (xu5_st1-no-fmc) and make_zpkg (xu5_st1-fmc_acq430) passed locally

2021-12-03 14:01 UTC, thomascobb commented
yes, this is a lack of RAM in the github runners, we are looking at a different solution

2022-01-24 09:48 UTC, Araneidae requested changes
This pull request seems to have a lot of unexpected changes, and this is making it harder to review than it ought to be.

Firstly, there is an alarming amount of formatting churn, layout changes, extra unrelated comments, file permission changes, etc.

Secondly, and more importantly, it strikes me that a lot of this pull request involves changes which have nothing to do with simply adding three more capture attributes.  I don't feel happy taking this review any further until we understand why these extra changes are in this PR.

In fact most of the files seem to have significant changes which have nothing to do with the sum^2 calculation.  Are these changes part of other bug fixes ... or are they errors introduced when merging master ... or something else I'm missing.

2022-01-24 09:48 UTC, Araneidae commented on modules/pcap/hdl/pcap_bus_delay.vhd
> +signal SHIFT_SUM_r1   : std_logic_vector(5 downto 0);
Just a minor coding style question: I don't understand why these intermediate signals have been declared?  Why not just assign directly to the outputs?

To me this just makes the code even more verbose than it needs to be.

2022-01-24 09:48 UTC, Araneidae commented on modules/pcap/hdl/pcap_buffer.vhd
> -    --
I notice that the executable bit has been set for this file.  This appears to have happened to a number of other files in this commit; will try and gather a list for the final review.

2022-01-24 09:48 UTC, Araneidae commented on modules/pcap/hdl/pcap_core.vhd
> +pcap_armed_or_ARM <= (pcap_armed or ARM);
Redundant parentheses.

2022-01-24 09:48 UTC, Araneidae commented on modules/pcap/hdl/pcap_frame.vhd
> +signal trig_pulse_o     : std_logic_vector(PBUSW-1 downto 0);
I know this isn't part of this PR, these names already exist --- but, please, the `_o` extension is supposed to be reserved for output parameters _only_.

2022-01-24 11:12 UTC, shu-soleil commented
I'll try to reply and make needed corrections. Our service provider Thierry is not working on this project anymore but he is still here and can answer questions if necessary.

2022-01-24 14:01 UTC, Araneidae commented on tests/hdl/single_test.tcl
>  if {$argc > $MODULES_IND} {
Don't think this file is part of this PR

2022-04-07 08:07 UTC, Araneidae commented
Corresponding [PandABlocks-server](https://github.com/PandABlocks/PandABlocks-server) issue [#13](https://github.com/PandABlocks/PandABlocks-server/issues/13) now closed with push of [tag 3.0a2](https://github.com/PandABlocks/PandABlocks-server/releases/tag/3.0a2).

2022-06-29 09:46 UTC, merged